line-length = 80
target-version = "py310"

lint.select = [
    "E",  # pycodestyle Error
    "W",  # pycodestyle Warning
    "F",  # pyflakes
    "I",  # isort (import sorting)
    "N",  # pep8-naming
]
